version: '3.8'
services:
  stremio_addon:
    # Use pre-built image from GitHub Container Registry:
    # image: ghcr.io/i0-ox/custom-m3u-xcapi-egp-iptv-stremio:latest
    build: .
    container_name: stremio_addon
    ports:
      - "7000:7000"
    env_file:
      - .env
    restart: unless-stopped
    # depends_on:
    #   - redis

  # Optional Redis service
  # redis:
  #   image: redis:7-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
